openapi: 3.0.0
info:
  title: TesteCoral - Evaluation
  version: '0.1'
tags:
  - name: Quiz
  - name: Evaluation
paths:
  /evaluations:
    post:
      operationId: createEvaluation
      tags:
        - Evaluation
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
  /quizzes:
    get:
      operationId: getQuizzes
      tags:
        - Quiz
      summary: List all quizzes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/OffsetCount'
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Quiz'
    post:
      operationId: createQuiz
      tags:
        - Quiz
      summary: Create a quiz
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputQuiz'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
          headers:
            Location:
              description: URI of the new quiz
              schema:
                type: string
  '/quizzes/{quiz_id}':
    get:
      operationId: getQuizById
      tags:
        - Quiz
      summary: Get a quiz by Id
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz not found
components:
  schemas:
    Evaluation:
      allOf:
        - type: object
          properties:
            $id:
              type: string
        - $ref: '#/components/schemas/InputEvaluation'
    InputEvaluation:
      type: object
      properties:
        quiz_id:
          type: string
        subject_id:
          type: string
          description: The one who is being evaluated.
        answers:
          type: object
    InputQuiz:
      type: object
      properties:
        description:
          type: string
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
    OffsetCount:
      type: object
      properties:
        $offset:
          type: number
          format: integer
          example: 0
        $count:
          type: number
          format: integer
          example: 20
    Question:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
        description:
          type: string
        properties:
          type: object
    Quiz:
      allOf:
        - type: object
          properties:
            $id:
              type: string
        - $ref: '#/components/schemas/InputQuiz'
  headers:
    ExpiresAfter:
      description: date in UTC when token expires
      schema:
        type: string
        format: date-time
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
